// The 7 scroll panels. Copy + layout taken from the NOCTURNE/330 spec.
// `align` controls DOM placement (asymmetry rule: never center both car & copy,
// except the deliberate hero and the big-word design panel).
export const SECTIONS = [
  {
    id: 'hero',
    index: '00',
    label: 'Sheer driving pleasure',
    variant: 'hero',
    eyebrow: 'BMW · 2.0 TwinPower Turbo',
    title: ['THE', '330i'],
    sub: 'Sport sedan. Reimagined for the dark.',
    cta: 'Book a test drive',
  },
  {
    id: 'overview',
    index: '01',
    label: 'Overview',
    variant: 'left',
    eyebrow: 'The BMW 330i',
    title: ['The', 'BMW 330i'],
    body: 'A 2.0-litre TwinPower Turbo inline-four — 255 hp, 369 Nm, near 50:50 balance. Engineered to disappear into the road.',
    link: 'Learn more',
  },
  {
    id: 'design',
    index: '02',
    label: 'Design',
    variant: 'word',
    eyebrow: 'Design language',
    word: 'PROPORTION',
    body: 'Long hood, set-back cabin, short overhangs — frameless surfacing and the signature kidney grille, drawn in one continuous line. 0.26 Cd.',
  },
  {
    id: 'performance',
    index: '03',
    label: 'Performance',
    variant: 'right',
    eyebrow: 'Performance',
    stat: { value: '0–100', unit: 'in 5.6s' },
    title: ['Lightning-fast', 'response'],
    body: '8-speed Steptronic Sport with launch control. 400 Nm of torque from just 1,550 rpm — response without a single delay.',
    telemetry: true,
  },
  {
    id: 'rear',
    index: '04',
    label: 'Rear',
    variant: 'left',
    eyebrow: 'Aerodynamics',
    title: ['Power', 'from behind'],
    body: 'Wide rear track, integrated diffuser and dual M Sport exhaust. Full-LED tail bars stretch the car wide and low.',
  },
  {
    id: 'assist',
    index: '05',
    label: 'Driver assistance',
    variant: 'right',
    eyebrow: 'Intelligence',
    title: ['Always one', 'step ahead'],
    body: 'Driving Assistant: active cruise, lane keeping and collision warning. Intelligence that stays out of the way.',
  },
  {
    id: 'powertrain',
    index: '06',
    label: 'Powertrain',
    variant: 'outro',
    eyebrow: 'M TwinPower Turbo',
    stat: { value: '255', unit: 'hp' },
    title: ['M TwinPower', 'Turbo'],
    specs: [
      { k: 'Power', v: '255 hp' },
      { k: 'Torque', v: '369 Nm' },
      { k: '0–100 km/h', v: '5.6 s' },
      { k: 'Top speed', v: '250 km/h' },
      { k: 'Displacement', v: '1,998 cc' },
      { k: 'Drive', v: 'Rear / xDrive' },
    ],
    body: 'Twin-scroll turbocharging, VALVETRONIC and High Precision Injection. The heart of every 3 Series.',
    cta: 'Book now',
  },
]
